

version: "3.3"

services:

   server:
       build: ./dock
       ports:
         - "80:5000"
       
      
       environment:
         - FLASK_ENV:developement
       networks:
         - monitoring

   client:
       build: ./front
       ports:
         - "3000:3000"
       depends_on:
         - server
       networks:
         - monitoring
       container_name: frontend
       
   prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090


       
networks:
  monitoring:
    driver: bridge
