
version: "1.0"

services:

   server:
       build: ./dock
       ports:
         - "80:5000"
       
      
       environment:
         - FLASK_ENV:developement
       networks:
         - monitoring

   client:
       build: ./front
       ports:
         - "3002:3000"
       depends_on:
         - server
       networks:
         - monitoring
       container_name: frontend
networks:
  monitoring:
    driver: bridge
