global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets:
      - 'localhost:9090' 

  - job_name: 'grafana'
    static_configs:
    - targets:
      - 'host.docker.internal:3100'

  - job_name: 'client'
    static_configs:
    - targets: ["client:3002"]

  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']


  